create table file_types (
    key varchar(32) not null primary key,
    description varchar not null
);
comment on table file_types is 'Describes the different types of files that can be associated with a job';
comment on column file_types.key is 'Unique identifier for the file type';
comment on column file_types.description is 'Human-readable description of what this file type represents';

insert into file_types (key, description) values
  ('SOURCE_VIDEO', 'Original video file uploaded for processing'),
  ('EXTRACTED_AUDIO', 'Audio file extracted from the source video'),
  ('WHISPER_TRANSCRIPT', 'Raw transcript generated by Whisper from the audio'),
  ('DIARIZATION_RTTM', 'Speaker diarization data in RTTM format'),
  ('DIARIZED_TRANSCRIPT', 'Transcript with speaker identification added'),
  ('CLASS_ANALYSIS', 'Final CLASS analysis output');

-- Add file_type column to job_files with foreign key constraint
alter table job_files
    add column file_type varchar(32) not null,
    add constraint fk_job_files_file_type
        foreign key (file_type) references file_types(key);

comment on column job_files.file_type is 'Type of file - maps to file_types table';

-- Add an index for faster lookups by job_id + file_type
create index idx_job_files_job_id_file_type
    on job_files(job_id, file_type);